project:
  type: website
  output-dir: _site

website:
  title: "Galileo Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: usage/getting-started.qmd
        text: Usage
      - href: reports/efficiency.qmd
        text: Reports
      - href: data-science/workflow.qmd
        text: Data Science
      - href: business/context.qmd
        text: Business Logic
      - href: technical-reference/viz.qmd
        text: Technical Reference

  sidebar:
    - title: "Usage"
      contents:
        - usage/getting-started.qmd
        - usage/creating-reports.qmd
    - title: "Reports"
      contents:
        - reports/efficiency.qmd
        - reports/microbiology.qmd
        - reports/h2o.qmd
    - title: "Data Science"
      contents:
        - data-science/workflow.qmd
        - data-science/insights.qmd
    - title: "Business Logic"
      contents:
        - business/context.qmd
        - business/metrics.qmd
        - business/operational-ranges.qmd
        - business/sackoff-analysis.qmd
    - title: "Technical Reference"
      contents:
        - technical-reference/viz.qmd
        - technical-reference/s3.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    code-fold: show
    code-copy: true
    highlight-style: github
